#!/bin/bash

NAME="{{ project_name }}"                            # Name of the application
DJANGODIR={{ project_home }}/src/{{ project_name }}/ # Django project directory
SOCKFILE={{ project_home }}/run/gunicorn.sock        # we will communicte using this unix socket
PIDFILE={{ project_home }}/run/gunicorn.pid
USER={{ project_name }}                              # the user to run as
GROUP={{ project_name }}                             # the group to run as
NUM_WORKERS=5                                        # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE={{ project_name }}.settings   # which settings file should Django use
DJANGO_WSGI_MODULE={{ project_name }}.wsgi           # WSGI module name

echo "Starting $NAME"

# Activate the virtual environment
cd $DJANGODIR
source {{ project_home }}/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
export PROD=1
export HOME="{{ project_home }}"

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:$SOCKFILE \
  --pid $PIDFILE
